### ISSUE TITLE
Global Shortcut to a "the road so far"-widget

### ISSUE THREAD

**Issue by kronn** [gtimelog/gtimelog#104]
Some other apps have or at least offer global shortcut to a core subset of functionality. For example, I can add a task to my Task-App with one global shortcut.

Is something like this available or configurable for gtimelog? 

I imagine something to just enter, what I did until the current moment, nothing else. 

If not, how can I help to implement this at least for Ubuntu 16.04?

**Comment by mgedmin** [comment]
I've set up a global keyboard shortcut (Super+G) in my GNOME System Preferences' Keyboard panel to run `gtimelog`.  It's supposed to bring the the gtimelog window to front so you can enter whatever you've been doing:

![ekrano nuotrauka is 2017-07-26 17-50-12](https://user-images.githubusercontent.com/159967/28627598-f23d75a2-722a-11e7-903b-3981892cb14f.png)
![ekrano nuotrauka is 2017-07-26 17-50-26](https://user-images.githubusercontent.com/159967/28627602-f584f050-722a-11e7-9ddd-ef6b25ae5e8c.png)

At one point this stopped working reliably for me because GNOME Shell's focus stealing prevention got way too aggressive.  As a workaround the current git master hides and shows the window instead of trying to bring it to front.  This kind of works, except on Wayland it forgets the window position and moves it to wherever the window manager wants to put it, which is near the top-left corner of the leftmost monitor. 

 *sigh*

Is this more or less what you had in mind?

**Comment by kronn** [comment]
No, not really, but I think I can change my idea. :-) The original plan was to have a separate "enter one line" widget, which I can control independently from the main window.

With the approach you outlined, I might get a "good enough" solution. I'll close this for now. Thanks.
