### ISSUE TITLE
Time left at work confusing

### ISSUE THREAD

**Issue by codingforfun** [gtimelog/gtimelog#119]
I’ve configured 8h worktime and 9h officetime. 
After around 7h work but 9:37h office time, gtimelog reports:
```
Total work done: 7 h 2 min (24 h 33 min this week, 8 h 11 min per day)
Total slacking: 1 h 0 min (3 h 15 min this week, 1 h 5 min per day)
Time left at work: 0 h 0 min (should've finished at 18:15)
At office today: 9 h 35 min (0 h 35 min overtime)`
```

I find the `Time left at work` strange. Obviously it is computed using office time, but this isn’t really helpful. Most helpful would be if if would tell how much (paid) worktime is still missing. Or it should name something like `Time left at office`. However  `Time left at office` is barely useful I think. 

Bug report or change request? I don’t know what was the intention here in the first place.

**Comment by kronn** [comment]
I add two ** for break that do not count towards my office time (like lunch) and one * for things that are work-time, but "slacking" in terms of gtimelog (I can use that hint to determine if the job can be invoiced to a client or not). This star-notation is official and therefore works quite well.

**Comment by mgedmin** [comment]
Here's how "time left at work" is calculated, simplified:

  time_left_at_work = configured_work_time_hours - total_work_done_today_including_current_entry

where

  total_work_done_today_including_current_entry = total_work_during_today + time_since_last_entry

If the entry box contains a `**`, time_since_last_entry is zeroed.

IIRC it was done this way because I was annoyed when the "time left at work" figure was staying constant while I was working on some longer task, so I made gtimelog assume that you're working unless you tell it explicitly that you're not (by pre-entering the slacking entry and not hitting Enter).


Sometimes I wish I had the organizational skills to set up a crowdfunding effort to hire a technical writer and get some documentation done for gtimelog...

**Comment by codingforfun** [comment]
Ok. Thanks. I got it.  I understand now that it’s perfectly Ok how it is. 

Another thing that kind of confused me is that there is overtime w.r.t. office hours but not the equivalent in terms of work hours.

E.g. for today:
```
Total work done: 9 h 27 min (35 h 50 min this week, 8 h 57 min per day)
Total slacking: 1 h 0 min (4 h 15 min this week, 1 h 3 min per day)
Time left at work: 0 h 0 min (should've finished at 18:15)
At office today: 10 h 30 min (1 h 30 min overtime)
```
Would be nice to have:
```
…
Time left at work: 0 h 0 min (should've finished at 18:15 – 1 h 27 min overtime)
…
```
