### ISSUE TITLE
Task pane won't open

### ISSUE THREAD

**Issue by rvanlaar** [gtimelog/gtimelog#219]
The task pane won't show when pressing F9 or clicking the button.
Edit task list does work.

The fix was to reset all gsettings:

gsettings reset-recursively org.gtimelog

**Comment by mgedmin** [comment]
I'm guessing what happened is you somehow shrunk the task pane to 0 pixels in width, and, unfortunately, gtimelog remembers that in gsettings.

I can easily reproduce.

This is nasty, since once you shrink the pane too much, you can no longer grab it with the mouse to enlarge it again -- the mouse cursor starts resizing the entire window.

A better workaround would be `gsettings reset org.gtimelog task-pane-position`, but there should be some kind of minimum width to prevent this situation from arising in the first place.

**Comment by mgedmin** [comment]
AFAIU the way to set the minimum sizes for the two children of the GtkPaned is by setting the `width-request` property on the children.  This doesn't help: I set both panes to be at least 50 px, and yet the paned allows me to shrink either of them to 0.

Help?

**Comment by mgedmin** [comment]
Oh, I also have to set the child property `shrink` to False!

**Comment by mgedmin** [comment]
Fixed in git master.

**Comment by rvanlaar** [comment]
Awesome how quickly you're able to fix a bug.

While reproducing, I noticed the following:
It happens when task-pane-position is 1 less than the window-size width.

Looking at my shell history I did set the task-pane-position to the default of 600. 
It didn't matter because of the smaller window size.

**Comment by mgedmin** [comment]
Ooh, that is an interesting corner case.  Let's see

- make the window narrow
- close gtimelog
- `gsettings reset org.gtimelog task-pane-position`
- `gsettings get org.gtimelog task-pane-position` (shows 600)
- start gtimelog
- press F9 to show the task pane

Ok, it shows up as 50 pixels, unusable, but resizable.  Good.

Interestingly, I probably intentionally made the task pane shrinkable to 0 years ago, because with the GTK 2 default theme and thicker window borders common during that age that was still a recoverable situation.
