### ISSUE TITLE
Logs on 11:11 change formating

### ISSUE THREAD

**Issue by JP-Garcia** [gtimelog/gtimelog#256]
Somehow any log involving the time 11:11 removes the tab character in the app formatting. The log itself is fine. See attached screenshots.

![Screenshot from 2024-07-11 11-23-35](https://github.com/gtimelog/gtimelog/assets/104278439/fa52ba31-74ad-480b-a71c-87e608a3f93f)
![Screenshot from 2024-07-11 11-25-38](https://github.com/gtimelog/gtimelog/assets/104278439/df0df615-ad0a-4d79-a011-59fc94ce4715)
![Screenshot from 2024-07-11 11-29-24](https://github.com/gtimelog/gtimelog/assets/104278439/dd66b63f-172e-41c7-930c-45dcc7291397)
![image](https://github.com/gtimelog/gtimelog/assets/104278439/1dd00c2a-ecf5-47ae-ad1b-cc6640908b83)

**Comment by mgedmin** [comment]
The text with all those 1s is narrower so an earlier tab stop gets used instead of the right one.

I thought I was [setting up two custom tab stops](https://github.com/gtimelog/gtimelog/blob/c7c3f2d8b72e9e8d66ff5fb47513c93228afe2bd/src/gtimelog/main.py#L1456-L1457) (at 9em and 12.5em) correctly, but apparently not.  Hmm, if I use the GTK Inspector to make the LogView widget editable, I see only one custom tab stop:

![paveikslas](https://github.com/user-attachments/assets/68b77048-e294-4a53-a777-93a00ec4e2f1)

I wonder why?  Time to read the documentation on Pango.TabArray.

**Comment by mgedmin** [comment]
Should be fixed in commit 3014d7de.
