### ISSUE TITLE
The correction system isn't working after midnight

### ISSUE THREAD

**Issue by chronossc** [gtimelog/gtimelog#33]
Hello :). I have testing the 'correction system' as you example in docs but it is not really working, there is a example when I try to entry with `16:45 task 3`:

![image](https://cloud.githubusercontent.com/assets/208856/6861935/6f4c1854-d41d-11e4-8cd6-f28a3a4ecc11.png)

**Comment by mgedmin** [comment]
Looks like a bug to me.  In [this bit of code](https://github.com/gtimelog/gtimelog/blob/4228e41f46b1383dba22de4f425122f31eb5e28e/src/gtimelog/main.py#L962-L971):
```python
                now = datetime.datetime.now()
                now = now.replace(hour=h, minute=m, second=0, microsecond=0)
                if self.timelog.valid_time(now):
```
Since you're entering a correction after midnight, the date is different. 16:45 ends up being a time in the future, so [the validator](https://github.com/gtimelog/gtimelog/blob/4228e41f46b1383dba22de4f425122f31eb5e28e/src/gtimelog/timelog.py#L907-L913) discards it:
```python
    def valid_time(self, time):
        if time > datetime.datetime.now():
            return False
```
I think I need to replace the `datetime.datetime.now()` with something that pays attention to the "virtual midnight" setting and adjusts the date accordingly.

**Comment by chronossc** [comment]
I understand. If I have time today I dig into that code and try to fix it :), but no promises.

**Comment by shirishag75** [comment]
any update on this ?

**Comment by mgedmin** [comment]
I haven't had the time to look into this, no.

(I rarely work past midnight these days, so I never see this bug.  Also, I usually hit Ctrl-E and fix the timestamps directly in the text file.)

**Comment by mgedmin** [comment]
Uhh, there are more corner cases hiding here.  Now entering a correction of "00:15" when the time is 00:30 fails, because it thinks the 00:15 refers to a previous day.
