### ISSUE TITLE
No instructions to compile gtimelog

### ISSUE THREAD

**Issue by shirishag75** [gtimelog/gtimelog#39]
There are no instructions how to compile gtimelog. I do see a Makefile but as there are no instructions, it makes it harder. Doing a simple make results in :-

    ~/games/gtimelog$make
    rst2man gtimelog.rst > gtimelog.1
    rst2man gtimelogrc.rst > gtimelogrc.5

which doesn't look good to get the new binary.

**Comment by mgedmin** [comment]
GTimeLog is a Python application: there's no compilation step.  Just run it:
```
$ git clone https://github.com/gtimelog/gtimelog
$ cd gtimelog
$ ./gtimelog
```

This is documented at https://github.com/gtimelog/gtimelog/blob/master/README.rst#installing

You may need to install some dependencies first, e.g. on Ubuntu that would be:
```
$ sudo apt-get install python-gi gir1.2-gtk-3.0 gir1.2-pango-1.0
```

This is also documented at https://github.com/gtimelog/gtimelog/blob/master/README.rst#installing, but without listing specific package names for Ubuntu.

(The `make` command produces manual pages, should you wish to read them with `man` instead of looking at the ReStructuredText equivalent.  It's completely optional.)

**Comment by shirishag75** [comment]
I am on debian,  not ubuntu. 

If I'm reading it right,  the gtimelog source-code just calls main.py/ main.pyc  from the last two lines of gtimelog wrapper.

    from gtimelog.main import main
    main()

So essentially it's main.py/main.pyc and other $stuff. The gtimelog executable is nothing but a script which calls the other main.py/pyc and others.

**Comment by mgedmin** [comment]
That's right.
